; C:\Users\mwong\AppData\Roaming\WinSCP.ini
[Configuration\Security]
UseMasterPassword=0

[Sessions\deploy%40sftp.fabrikam.com]
HostName=sftp.fabrikam.com
UserName=deploy
PortNumber=22
FSProtocol=5
Password=C57E5D8F2A1C7D3E5B609481F2C3D4E5F60718293A4B5C6D7E8F90FABRIKAM
Shell=/bin/bash
LocalDirectory=C:\deploy\artifacts

[Sessions\ftpuser%40198.51.100.90]
HostName=198.51.100.90
UserName=ftpuser
PortNumber=21
FSProtocol=0
Password=D68F6E9F3B2D8E4F6C71A592F3D4E5F60718293A4B5C6D7E8F90WINSCPFAKE
Ftps=0
