find_program(CAITO_LLVM_AR NAMES llvm-ar REQUIRED)
find_program(CAITO_LLVM_RANLIB NAMES llvm-ranlib REQUIRED)

set(CMAKE_AR "${CAITO_LLVM_AR}" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${CAITO_LLVM_RANLIB}" CACHE FILEPATH "" FORCE)
set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")
set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")
